<a href="https://colab.research.google.com/github/kamalakk/Data-Analysis/blob/main/DataCleaningPandas1stSep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data cleaning pandas sep 1

In [3]:
import pandas as pd
df=pd.read_csv('/content/world_population.csv')
df.head(5)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [7]:
df.rename(columns={'2022 Population':'2022 Pop','2020 Population':'2020 Pop'},inplace=True)
df.head()

,Rank,CCA3,Country,Capital,Continent,2022 Pop,2020 Pop,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [8]:
df.isnull().any()

Rank                           False
CCA3                           False
Country                        False
Capital                        False
Continent                      False
2022 Pop                        True
2020 Pop                        True
2015 Population                 True
2010 Population                 True
2000 Population                 True
1990 Population                 True
1980 Population                 True
1970 Population                 True
Area (km²)                      True
Density (per km²)               True
Growth Rate                     True
World Population Percentage    False
dtype: bool

In [11]:
df[df['2020 Pop'].isna() == 1]

,Rank,CCA3,Country,Capital,Continent,2022 Pop,2020 Pop,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
13,91,AZE,Azerbaijan,Baku,Asia,10358074.0,NaN,9863480.0,9237202.0,8190337.0,7427836.0,6383060.0,5425317.0,86600.0,119.6082,1.0044,0.13

In [13]:
df['2020 Pop'] = df['2020 Pop'].fillna(0)
df.iloc[13]

Rank                                   91
CCA3                                  AZE
Country                        Azerbaijan
Capital                              Baku
Continent                            Asia
2022 Pop                       10358074.0
2020 Pop                              0.0
2015 Population                 9863480.0
2010 Population                 9237202.0
2000 Population                 8190337.0
1990 Population                 7427836.0
1980 Population                 6383060.0
1970 Population                 5425317.0
Area (km²)                        86600.0
Density (per km²)                119.6082
Growth Rate                        1.0044
World Population Percentage          0.13
Name: 13, dtype: object

In [16]:
df.duplicated().any()
#df[df['columname'].duplicated() == 1]
#df[df['columnname].isin(['nam1','name2','name3'])]

np.False_

In [18]:
df=df.drop_duplicates()

In [19]:
df.head()

,Rank,CCA3,Country,Capital,Continent,2022 Pop,2020 Pop,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00