<a href="https://colab.research.google.com/github/kamalakk/Data-Analysis/blob/main/groupbyPandas2ndSep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Group by pandas 2nd september 2026

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
df.groupby('time',observed=True)['total_bill'].mean()

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [10]:
df.groupby('time',observed=True)['total_bill'].mean().to_frame('Avg-Bill')

         Avg-Bill
time
Lunch   17.168676
Dinner  20.797159

In [12]:
df.groupby('time',observed=True)['total_bill'].mean().to_frame('Avg-Bill').reset_index()

     time   Avg-Bill
0   Lunch  17.168676
1  Dinner  20.797159

In [15]:
df.groupby('time',observed=True)['total_bill'].mean().to_frame('Avg-Bill').reset_index().sort_values('Avg-Bill', ascending=False)

     time   Avg-Bill
1  Dinner  20.797159
0   Lunch  17.168676

In [16]:
avgbill=df.groupby('time',observed=True)['total_bill'].mean().to_frame('Avg-Bill').reset_index().sort_values('Avg-Bill', ascending=False)
avgbill.head()

     time   Avg-Bill
1  Dinner  20.797159
0   Lunch  17.168676

In [17]:
df.groupby('time', observed=True)['total_bill'].count()

time
Lunch      68
Dinner    176
Name: total_bill, dtype: int64

In [18]:
df.groupby('time', observed=True)['total_bill'].size()

time
Lunch      68
Dinner    176
Name: total_bill, dtype: int64

In [19]:
df.groupby('time', observed=True)['total_bill'].nunique()

time
Lunch      64
Dinner    168
Name: total_bill, dtype: int64

In [20]:
df.groupby('time', observed=True)['total_bill'].max()

time
Lunch     43.11
Dinner    50.81
Name: total_bill, dtype: float64

In [21]:
df.groupby('time', observed=True)['total_bill'].min()

time
Lunch     7.51
Dinner    3.07
Name: total_bill, dtype: float64

In [22]:
df.groupby('time', observed=True)['total_bill'].sum()

time
Lunch     1167.47
Dinner    3660.30
Name: total_bill, dtype: float64

In [23]:
df.groupby('time', observed=True)['total_bill'].median()

time
Lunch     15.965
Dinner    18.390
Name: total_bill, dtype: float64

In [24]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [26]:
df.groupby('day', observed=True)['tip'].mean()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [28]:
df.groupby('sex', observed=True)['tip'].max().reset_index()

      sex   tip
0    Male  10.0
1  Female   6.5

In [32]:
df.groupby('day', observed=True)['tip'].quantile(.9)

day
Thur    4.920
Fri     4.060
Sat     4.802
Sun     5.035
Name: tip, dtype: float64

In [34]:
df.groupby('time', observed=True)['total_bill'].agg(['mean','sum','min','max'])

             mean      sum   min    max
time
Lunch   17.168676  1167.47  7.51  43.11
Dinner  20.797159  3660.30  3.07  50.81

In [36]:
df.groupby('time', observed=True)['total_bill'].agg(['mean','sum','min','max',np.median])

/tmp/ipykernel_3126/3703142163.py:1: FutureWarning: The provided callable <function median at 0x78fdb67b7240> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('time', observed=True)['total_bill'].agg(['mean','sum','min','max',np.median])

             mean      sum   min    max  median
time
Lunch   17.168676  1167.47  7.51  43.11  15.965
Dinner  20.797159  3660.30  3.07  50.81  18.390

In [37]:
df.groupby('time', observed=True)['total_bill'].agg(['mean','sum','min','max', 'median'])

             mean      sum   min    max  median
time
Lunch   17.168676  1167.47  7.51  43.11  15.965
Dinner  20.797159  3660.30  3.07  50.81  18.390

In [ ]:
df.groupby('time', observed=True)['total_bill'].agg(['mean','sum','min','max', 'median'])