<a href="https://colab.research.google.com/github/kamalakk/Data-Analysis/blob/main/PandasAggregateFn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aggragate function

In [35]:

import pandas as pd
#df = pd.read_csv('/content/Flavors.csv', index_col='Flavor')
df = pd.read_csv('/content/Flavors.csv')

df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [8]:
#df.mean(numeric_only=True)
#df.sum(numeric_only=True)
#df.min(numeric_only=True)
#df.max(numeric_only=True)
df.count()

Flavor            9
Base Flavor       9
Liked             9
Flavor Rating     9
Texture Rating    9
Total Rating      9
dtype: int64

In [9]:
#single column Flavor Rating	Texture Rating	Total Rating
df['Flavor Rating'].mean()
#df['Flavor Rating'].sum()
#df['Flavor Rating'].min()
#df['Flavor Rating'].max()
#df['Flavor Rating'].count()

np.float64(6.6000000000000005)

In [13]:
groupvar = df.groupby('Base Flavor')
#groupvar.mean(numeric_only=True)
#groupvar['Total Rating'].mean()
groupvar["Total Rating"].sum()

Base Flavor
Chocolate    47.1
Vanilla      68.1
Name: Total Rating, dtype: float64

Selection in Pandas

In [14]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [16]:
df[["Flavor Rating",	"Texture Rating",	"Total Rating"]]

   Flavor Rating  Texture Rating  Total Rating
0           10.0             8.0          18.0
1            8.8             7.6          16.6
2            4.7             5.0           9.7
3            6.9             6.5          13.4
4            8.2             7.0          15.2
5            2.3             3.4           5.7
6            6.5             6.0          12.5
7            3.8             5.0           8.8
8            8.2             7.1          15.3

In [18]:
# loc property
df.loc[1]

Flavor            Chocolate
Base Flavor       Chocolate
Liked                   Yes
Flavor Rating           8.8
Texture Rating          7.6
Total Rating           16.6
Name: 1, dtype: object

In [20]:
df

,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
Flavor,,,,,
Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
Chocolate,Chocolate,Yes,8.8,7.6,16.6
Vanilla,Vanilla,No,4.7,5.0,9.7
Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
Rocky Road,Chocolate,Yes,8.2,7.0,15.2
Pistachio,Vanilla,No,2.3,3.4,5.7
Cake Batter,Vanilla,Yes,6.5,6.0,12.5
Neapolitan,Vanilla,No,3.8,5.0,8.8
Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [21]:
df.loc['Vanilla']

Base Flavor       Vanilla
Liked                  No
Flavor Rating         4.7
Texture Rating        5.0
Total Rating          9.7
Name: Vanilla, dtype: object

In [26]:
#df.loc['Cake Batter',['Flavor Rating','Texture Rating']]
df.loc['Cookie Dough':'Cake Batter',['Flavor Rating','Texture Rating']]

              Flavor Rating  Texture Rating
Flavor
Cookie Dough            6.9             6.5
Rocky Road              8.2             7.0
Pistachio               2.3             3.4
Cake Batter             6.5             6.0

Integer location

In [29]:
#df.iloc[0:4]
df.iloc[0:4:2,0:3]

                    Base Flavor Liked  Flavor Rating
Flavor
Mint Chocolate Chip     Vanilla   Yes           10.0
Vanilla                 Vanilla    No            4.7

In [39]:

inputvar = input("Enter number ")

try:
     df.loc[inputvar]
except KeyError:
   print ("data not found")
#finally:
   # print("un expected finally block")

Enter number 4
data not found

Filtering

In [40]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [41]:
df[df['Flavor Rating'] >= 4]

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [43]:
#df[df['Flavor'] == 'Cookie Dough']
df[(df['Flavor'] == 'Cookie Dough') | (df['Flavor'] == 'Rocky Road')]

         Flavor Base Flavor Liked  Flavor Rating  Texture Rating  Total Rating
3  Cookie Dough     Vanilla   Yes            6.9             6.5          13.4
4    Rocky Road   Chocolate   Yes            8.2             7.0          15.2