<a href="https://colab.research.google.com/github/kamalakk/Data-Analysis/blob/main/PracticeDataCleaningSep3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=85c813c7f0ff8afe654e99f770cea6e330b33ca15bbcafe8c293260206526fee
  Stored in directory: /root/.cache/pip/wheels/aa/2b/71/ede4a3c3520a8374778c16c345e0e78e25d1ffe38f4c5c1e8a
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [ ]:
import pandas as pd
import numpy as np
from word2number import w2n
# A deliberately messy dataset
data = {
    'Name': [' John Doe ', 'JANE smith', 'Bob Johnson', ' john doe', 'ALICE WONG',
             'Bob Johnson', 'Mike Chen', 'Sara Lee', None, 'jane smith'],
    'Age': [28, '32', 45, 28, 'twenty-nine', 45, 37, 26, 40, '32'],
    'Email': ['john@x.com', 'jane@x.com', 'bob@X.com', 'JD@x.com', 'alice@x.com',
              'bob@x.com', None, 'sara@x.com', 'mr_x@x.com', 'JANE@x.com'],
    'Salary': ['$45,000', '$52,000', '$78,500', '$45,000', 'error',
               '$78,500', '$61,200', '$48,900', 'N/A', '$52,000'],
    'Join_Date': ['2021-05-01', '05/06/2020', '2022-01-15', '2021-05-01',
                  '2020-11-30', '15/01/2022', None, '2021-08-20', '2019-03-04', '2020-06-05'],
    'City': ['NYC', 'Los Angeles', 'Chicago', 'nyc', 'SFO', 'Chicago',
             'Austin', 'Seattle', 'NYC', 'LA']
}

In [ ]:
df=pd.DataFrame(data)
df

          Name          Age        Email   Salary   Join_Date         City
0    John Doe            28   john@x.com  $45,000  2021-05-01          NYC
1   JANE smith           32   jane@x.com  $52,000  05/06/2020  Los Angeles
2  Bob Johnson           45    bob@X.com  $78,500  2022-01-15      Chicago
3     john doe           28     JD@x.com  $45,000  2021-05-01          nyc
4   ALICE WONG  twenty-nine  alice@x.com    error  2020-11-30          SFO
5  Bob Johnson           45    bob@x.com  $78,500  15/01/2022      Chicago
6    Mike Chen           37         None  $61,200        None       Austin
7     Sara Lee           26   sara@x.com  $48,900  2021-08-20      Seattle
8         None           40   mr_x@x.com      N/A  2019-03-04          NYC
9   jane smith           32   JANE@x.com  $52,000  2020-06-05           LA

In [ ]:
df['Name'] = df['Name'].str.lower().str.title()
df

          Name          Age        Email   Salary   Join_Date         City
0    John Doe            28   john@x.com  $45,000  2021-05-01          NYC
1   Jane Smith           32   jane@x.com  $52,000  05/06/2020  Los Angeles
2  Bob Johnson           45    bob@X.com  $78,500  2022-01-15      Chicago
3     John Doe           28     JD@x.com  $45,000  2021-05-01          nyc
4   Alice Wong  twenty-nine  alice@x.com    error  2020-11-30          SFO
5  Bob Johnson           45    bob@x.com  $78,500  15/01/2022      Chicago
6    Mike Chen           37         None  $61,200        None       Austin
7     Sara Lee           26   sara@x.com  $48,900  2021-08-20      Seattle
8         None           40   mr_x@x.com      N/A  2019-03-04          NYC
9   Jane Smith           32   JANE@x.com  $52,000  2020-06-05           LA

In [ ]:
df.shape

(10, 6)

In [ ]:
df.dropna(inplace=True)
df

          Name          Age        Email   Salary   Join_Date         City
0    John Doe            28   john@x.com  $45,000  2021-05-01          NYC
1   Jane Smith           32   jane@x.com  $52,000  05/06/2020  Los Angeles
2  Bob Johnson           45    bob@X.com  $78,500  2022-01-15      Chicago
3     John Doe           28     JD@x.com  $45,000  2021-05-01          nyc
4   Alice Wong  twenty-nine  alice@x.com    error  2020-11-30          SFO
5  Bob Johnson           45    bob@x.com  $78,500  15/01/2022      Chicago
7     Sara Lee           26   sara@x.com  $48,900  2021-08-20      Seattle
9   Jane Smith           32   JANE@x.com  $52,000  2020-06-05           LA

In [ ]:
df.reset_index(drop=True,inplace=True)
df

          Name          Age        Email   Salary   Join_Date         City
0    John Doe            28   john@x.com  $45,000  2021-05-01          NYC
1   Jane Smith           32   jane@x.com  $52,000  05/06/2020  Los Angeles
2  Bob Johnson           45    bob@X.com  $78,500  2022-01-15      Chicago
3     John Doe           28     JD@x.com  $45,000  2021-05-01          nyc
4   Alice Wong  twenty-nine  alice@x.com    error  2020-11-30          SFO
5  Bob Johnson           45    bob@x.com  $78,500  15/01/2022      Chicago
6     Sara Lee           26   sara@x.com  $48,900  2021-08-20      Seattle
7   Jane Smith           32   JANE@x.com  $52,000  2020-06-05           LA

In [ ]:
df.drop_duplicates(subset = ['Name', 'Email'], inplace=True)
df

          Name          Age        Email   Salary   Join_Date         City
0    John Doe            28   john@x.com  $45,000  2021-05-01          NYC
1   Jane Smith           32   jane@x.com  $52,000  05/06/2020  Los Angeles
2  Bob Johnson           45    bob@X.com  $78,500  2022-01-15      Chicago
3     John Doe           28     JD@x.com  $45,000  2021-05-01          nyc
4   Alice Wong  twenty-nine  alice@x.com    error  2020-11-30          SFO
5  Bob Johnson           45    bob@x.com  $78,500  15/01/2022      Chicago
6     Sara Lee           26   sara@x.com  $48,900  2021-08-20      Seattle
7   Jane Smith           32   JANE@x.com  $52,000  2020-06-05           LA

In [ ]:
df['Email'] = df['Email'].str.lower().str.title()
df

          Name          Age        Email   Salary   Join_Date         City
0    John Doe            28   John@X.Com  $45,000  2021-05-01          NYC
1   Jane Smith           32   Jane@X.Com  $52,000  05/06/2020  Los Angeles
2  Bob Johnson           45    Bob@X.Com  $78,500  2022-01-15      Chicago
3     John Doe           28     Jd@X.Com  $45,000  2021-05-01          nyc
4   Alice Wong  twenty-nine  Alice@X.Com    error  2020-11-30          SFO
5  Bob Johnson           45    Bob@X.Com  $78,500  15/01/2022      Chicago
6     Sara Lee           26   Sara@X.Com  $48,900  2021-08-20      Seattle
7   Jane Smith           32   Jane@X.Com  $52,000  2020-06-05           LA

In [ ]:
df.drop_duplicates(subset = ['Name', 'Email'], inplace=True)
df

          Name          Age        Email   Salary   Join_Date         City
0    John Doe            28   John@X.Com  $45,000  2021-05-01          NYC
1   Jane Smith           32   Jane@X.Com  $52,000  05/06/2020  Los Angeles
2  Bob Johnson           45    Bob@X.Com  $78,500  2022-01-15      Chicago
3     John Doe           28     Jd@X.Com  $45,000  2021-05-01          nyc
4   Alice Wong  twenty-nine  Alice@X.Com    error  2020-11-30          SFO
6     Sara Lee           26   Sara@X.Com  $48,900  2021-08-20      Seattle

name cleaning done.

Age column

Convert to numeric, handling the text value 'twenty-nine' (map it to 29)
Report how many null/missing result

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 6
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       6 non-null      object
 1   Age        6 non-null      object
 2   Email      6 non-null      object
 3   Salary     6 non-null      object
 4   Join_Date  6 non-null      object
 5   City       6 non-null      object
dtypes: object(6)
memory usage: 336.0+ bytes

In [ ]:
def convert_age(x):
    try:
        # Try converting as integer first
        return int(x)
    except ValueError:
        try:
            # Convert word to number
            return w2n.word_to_num(x)
        except:
            # If both fail, return NaN or some default value
            return None
# Apply the function to the 'age' column
df['Age'] = df['Age'].apply(convert_age)

In [ ]:
df

          Name  Age        Email   Salary   Join_Date         City
0    John Doe    28   John@X.Com  $45,000  2021-05-01          NYC
1   Jane Smith   32   Jane@X.Com  $52,000  05/06/2020  Los Angeles
2  Bob Johnson   45    Bob@X.Com  $78,500  2022-01-15      Chicago
3     John Doe   28     Jd@X.Com  $45,000  2021-05-01          nyc
4   Alice Wong   29  Alice@X.Com    error  2020-11-30          SFO
6     Sara Lee   26   Sara@X.Com  $48,900  2021-08-20      Seattle

In [ ]:
df['Age'].info()

<class 'pandas.core.series.Series'>
Index: 6 entries, 0 to 6
Series name: Age
Non-Null Count  Dtype
--------------  -----
6 non-null      int64
dtypes: int64(1)
memory usage: 96.0 bytes

In [ ]:
#df['Age'].isnull().any()
df['Age'].isnull().sum()

np.int64(0)

In [ ]:
import numpy as np

In [ ]:
df['Salary'] = df['Salary'].replace(['NA', 'Missing', 'missing', 'N/A','error', ''], np.nan)

df['Salary'] = (
    df['Salary']
    .str.replace('[\$,]', '', regex=True)
    .astype(float)          # intermediate float allows NaN to survive
    .astype('Int64')        # nullable integer dtype (keeps NaN)
)
df

<>:5: SyntaxWarning: invalid escape sequence '\$'
<>:5: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipykernel_3401/4030338461.py:5: SyntaxWarning: invalid escape sequence '\$'
  .str.replace('[\$,]', '', regex=True)

AttributeError: Can only use .str accessor with string values!

In [ ]:
df

          Name  Age        Email  Salary   Join_Date         City
0    John Doe    28   John@X.Com   45000  2021-05-01          NYC
1   Jane Smith   32   Jane@X.Com   52000  05/06/2020  Los Angeles
2  Bob Johnson   45    Bob@X.Com   78500  2022-01-15      Chicago
3     John Doe   28     Jd@X.Com   45000  2021-05-01          nyc
4   Alice Wong   29  Alice@X.Com    <NA>  2020-11-30          SFO
6     Sara Lee   26   Sara@X.Com   48900  2021-08-20      Seattle

In [ ]:
df['Join_Date'].unique()

array(['2021-05-01', '05/06/2020', '2022-01-15', '2020-11-30',
       '2021-08-20'], dtype=object)

In [ ]:
df['Join_Date']=df['Join_Date'].str.replace('/', '-')
df

          Name  Age        Email  Salary   Join_Date         City
0    John Doe    28   John@X.Com   45000  2021-05-01          NYC
1   Jane Smith   32   Jane@X.Com   52000  05-06-2020  Los Angeles
2  Bob Johnson   45    Bob@X.Com   78500  2022-01-15      Chicago
3     John Doe   28     Jd@X.Com   45000  2021-05-01          nyc
4   Alice Wong   29  Alice@X.Com    <NA>  2020-11-30          SFO
6     Sara Lee   26   Sara@X.Com   48900  2021-08-20      Seattle

In [43]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'], format='mixed')

# 2. Convert to the specific dd-mmm-yyyy string format
df['Join_Date'] = df['Join_Date'].dt.strftime('%d-%b-%Y')

In [44]:
df

          Name  Age        Email  Salary    Join_Date         City
0    John Doe    28   John@X.Com   45000  01-May-2021          NYC
1   Jane Smith   32   Jane@X.Com   52000  06-May-2020  Los Angeles
2  Bob Johnson   45    Bob@X.Com   78500  15-Jan-2022      Chicago
3     John Doe   28     Jd@X.Com   45000  01-May-2021          nyc
4   Alice Wong   29  Alice@X.Com    <NA>  30-Nov-2020          SFO
6     Sara Lee   26   Sara@X.Com   48900  20-Aug-2021      Seattle

In [45]:
city_disc = {
    'NYC': 'New York',
    'Los Angeles': 'Los Angeles',
    'SFO': 'San Francisco',
    'Chicago': 'Chicago',
    'Seattle': 'Seattle',
    'nyc' : 'New York'
}

In [51]:
df['City'] = df['City'].str.upper()
city_mapping_upper_keys = {k.upper(): v for k, v in city_disc.items()}
df['City'] = df['City'].replace(city_mapping_upper_keys)
df['City'] = df['City'].str.title()
df

          Name  Age        Email  Salary    Join_Date           City
0    John Doe    28   John@X.Com   45000  01-May-2021       New York
1   Jane Smith   32   Jane@X.Com   52000  06-May-2020    Los Angeles
2  Bob Johnson   45    Bob@X.Com   78500  15-Jan-2022        Chicago
3     John Doe   28     Jd@X.Com   45000  01-May-2021       New York
4   Alice Wong   29  Alice@X.Com    <NA>  30-Nov-2020  San Francisco
6     Sara Lee   26   Sara@X.Com   48900  20-Aug-2021        Seattle

In [52]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
6    False
dtype: bool

In [53]:
df['Salary'].isnull().sum()

np.int64(1)

In [54]:
df.isnull().sum()

Name         0
Age          0
Email        0
Salary       1
Join_Date    0
City         0
dtype: int64